version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /pythonapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /pythonapp/docker-credentials/password

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - docker build -t "$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:jun29-06" .
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin docker.io
      - docker push "$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:jun29-06"
      - docker logout
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app
    
