version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - docker build -t "simple-python-flaskapp:jul17" .
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 871042891378.dkr.ecr.ap-southeast-1.amazonaws.com
      - docker tag simple-python-flaskapp:jul17 871042891378.dkr.ecr.ap-southeast-1.amazonaws.com/myaws-dockerhub:simple-python-flaskapp
      - docker push 871042891378.dkr.ecr.ap-southeast-1.amazonaws.com/myaws-dockerhub:simple-python-flaskapp
      - docker logout
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
     - '**/*'
